# Generated by Django 3.0.7 on 2020-06-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IfThen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup', models.TextField()),
                ('player', models.TextField()),
                ('conf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lift', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
